#!/usr/bin/env bash

# Remove existing folders
rm -rf $HOME/.screenlayout &>/dev/null
rm -rf $HOME/.config/autorandr &>/dev/null

# Unlink existing folders
unlink $HOME/.screenlayout &>/dev/null
unlink $HOME/.config/autorandr &>/dev/null

# Make links
ln -sf ./files/autorandr $HOME/.config/autorandr
ln -sf ./files/screenlayout $HOME/.screenlayout
